# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - kenjaccreations

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://clientswebsite.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8f7939464de34ed9bbb1ee5a4e385327 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a9accdbcb3df4728b86fa6c3fa93719e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: clientswebsite.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8f7939464de34ed9bbb1ee5a4e385327 }}/kenjaccreations-app-1:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kenjaccreations'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ec16821ee75f48288af404b7a588c1a9 }}
        images: 'clientswebsite.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8f7939464de34ed9bbb1ee5a4e385327 }}/kenjaccreations-app-1:${{ github.sha }}'